name: Enjektor-Yapici
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Derle
        run: g++ enjector.cpp -o KebapEnjektor.exe -lcomdlg32
      - name: Yukle
        uses: actions/upload-artifact@v4
        with:
          name: Enjektor-Dosyasi
          path: KebapEnjektor.exe
